#!/bin/bash

PROJECT_PATH="."

kill_it() {
    (ps aux | egrep "$1" | egrep -v grep | awk '{ print $2 }' | xargs kill -9 &> /dev/null)
}

setup() {
    echo "Setup"
    set -e
    pushd $PROJECT_PATH
    echo "Copy Settings"
    cat src/brainiak/settings_ci.py >> src/brainiak/settings.py
    echo "Install Dependencies"
    make install
}

tear_down() {
    git checkout .
    popd
}

unit() {
    setup
    echo "Running unit tests"
    make unit
    tear_down
}

integration() {
    setup
    echo "Running integration tests"
    make integration
    tear_down
}

violations() {
    set -e
    pushd $PROJECT_PATH
    make pep8 2>&1 > pep8.report
    make pep8_tests 2>&1 > pep8_test.report
    popd
}


if [ $1 ]; then
    . /usr/local/bin/virtualenvwrapper.sh
    workon brainiak
    $1
fi
