#!/bin/bash

PROJECT_PATH="."

kill_it() {
    (ps aux | egrep "$1" | egrep -v grep | awk '{ print $2 }' | xargs kill -9 &> /dev/null)
}

unit() {
    set -e
    pushd $PROJECT_PATH
    echo "Executando testes de unidade..."
    make install
    make unit
    popd
}

integration() {
    set -e
    pushd $PROJECT_PATH
    echo "Executando testes funcionais..."
    make install
    make integration
    popd
}

violations() {
    set -e
    pushd $PROJECT_PATH
    make pep8 2>&1 > pep8.report
    make pep8_tests 2>&1 > pep8_test.report
    popd
}


if [ $1 ]; then
    . /usr/local/bin/virtualenvwrapper.sh
    workon brainiak
    $1
fi
